name: 'Jacoco report'
description: 'This is a basic github action for jacoco report'
inputs:
  path:
    description: 'path of the generated jacoco xml file'
    required: false
  paths:
    description: 'paths of the generated jacoco xml files'
    required: false
  rules-path:
    description: 'path of the json files with minimum coverage for each module'
    required: true
  token:
    description: 'Github personal token to add commits to PR'
    required: true
  title:
    description: 'Optional title for the PR comment'
    required: true
outputs:
  coverage-overall:
    description: 'The overall coverage of the job'

runs:
  using: node16
  main: 'dist/index.js'

branding:
  icon: file-text
  color: green